#!/bin/bash
# Generated by Copilot
# Docker management script for Universal Downloader

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

IMAGE_NAME="universal-downloader"
CONTAINER_NAME="universal-downloader-app"

show_help() {
    echo -e "${BLUE}Universal Downloader Docker Management${NC}"
    echo ""
    echo "Usage: $0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  build    Build the Docker image"
    echo "  run      Run the container (builds if needed)"
    echo "  stop     Stop the running container"
    echo "  restart  Restart the container"
    echo "  logs     Show container logs"
    echo "  clean    Remove container and image"
    echo "  help     Show this help message"
}

build_image() {
    echo -e "${BLUE}Building Docker image...${NC}"
    docker build -t $IMAGE_NAME .
    echo -e "${GREEN}Image built successfully!${NC}"
}

run_container() {
    # Check if container is already running
    if docker ps -q -f name=$CONTAINER_NAME | grep -q .; then
        echo -e "${BLUE}Container is already running!${NC}"
        echo "Access the API at: http://localhost:3000"
        return
    fi

    # Build image if it doesn't exist
    if ! docker image inspect $IMAGE_NAME >/dev/null 2>&1; then
        build_image
    fi

    echo -e "${BLUE}Starting container...${NC}"
    docker run -d --name $CONTAINER_NAME -p 3000:3000 $IMAGE_NAME
    echo -e "${GREEN}Container started successfully!${NC}"
    echo "Access the API at: http://localhost:3000"
}

stop_container() {
    echo -e "${BLUE}Stopping container...${NC}"
    docker stop $CONTAINER_NAME 2>/dev/null || echo "Container not running"
    docker rm $CONTAINER_NAME 2>/dev/null || echo "Container not found"
    echo -e "${GREEN}Container stopped and removed!${NC}"
}

restart_container() {
    stop_container
    run_container
}

show_logs() {
    echo -e "${BLUE}Showing container logs...${NC}"
    docker logs -f $CONTAINER_NAME
}

clean_all() {
    echo -e "${BLUE}Cleaning up...${NC}"
    docker stop $CONTAINER_NAME 2>/dev/null || true
    docker rm $CONTAINER_NAME 2>/dev/null || true
    docker rmi $IMAGE_NAME 2>/dev/null || true
    echo -e "${GREEN}Cleanup completed!${NC}"
}

case "$1" in
    build)
        build_image
        ;;
    run)
        run_container
        ;;
    stop)
        stop_container
        ;;
    restart)
        restart_container
        ;;
    logs)
        show_logs
        ;;
    clean)
        clean_all
        ;;
    help|--help|-h)
        show_help
        ;;
    "")
        echo -e "${RED}No command specified!${NC}"
        show_help
        exit 1
        ;;
    *)
        echo -e "${RED}Unknown command: $1${NC}"
        show_help
        exit 1
        ;;
esac